name: qrsimplescanner
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5
  mobile_scanner: ^1.0.0
  url_launcher: ^6.1.0


dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_icon.jpg"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
